local wp = {
	-- https://gitlab.freedesktop.org/pipewire/wireplumber/-/blob/master/lib/wp/proxy.h
	WP_PROXY_FEATURE_BOUND = 1,
	WP_PIPEWIRE_OBJECT_FEATURE_INFO = 16,
	WP_PIPEWIRE_OBJECT_FEATURE_PARAM_PROPS = 32,
	WP_PIPEWIRE_OBJECT_FEATURE_PARAM_FORMAT = 64,
	WP_PIPEWIRE_OBJECT_FEATURE_PARAM_PROFILE = 128,
	WP_PIPEWIRE_OBJECT_FEATURE_PARAM_PORT_CONFIG = 256,
	WP_PIPEWIRE_OBJECT_FEATURE_PARAM_ROUTE = 512,
}

return wp
